[packages]
    [packages.homebrew.common]
        casks = [
            "1password-cli",                # 1Password CLI tooling
            "gpg-suite",                    # GPG Tooling
            "iterm2",                       # Terminal emulator
            "visual-studio-code",           # VS Code Editor
            "dropbox",
            "tailscale",
            "carbon-copy-cloner",
            "alfred",
            "rocket",
            "keyboard-maestro",
        ]
        formulae = [
            "bat",                          # Bat with syntax highlighting and Git integration
            "chezmoi",                      # Dotfile manager
            "coreutils",
            "fzf",                          # Fuzzy finder
            "ghostscript",                  # Interpreter for PostScript and PDF
            "git-filter-repo",              # Utility to rewrite git history
            "git-fresh",                    # Utility to keep git repos fresh
            "git",
            "gum",                          # Provides pretty shell-scripts
            "jq",                           # Lightweight and flexible command-line JSON processor
            "mas",                          # Mac App Store command-line interface
            "oh-my-posh",                   # Zsh theme
            "tealdeer",                     # A faster implementation of tldr man pages in rust
            "zoxide",                       # A faster way to navigate your filesystem
            "openssl@3",                    # Cryptography and SSL/TLS toolkit
            "readline",                     # Command linte editing library
            "libyaml",                      # YAML parser
            "gmp",                          # GNU precision math library
            "dockutil",                     # Tool for managing dock items
            "eza",                          # LS replacement
            "restic",                       # Backup tool
            "flock",                        # Multi-platform Flock(1) replacement
        ]

    [packages.homebrew.dev_computer]
        casks = [
            "slack",
            "tower",
            "docker",
            "omnifocus",
            "sketch",
            "discord",
            "zoom",
            "obsidian",
            "cleanshot",
        ]
        formulae = [
            "hugo",                         # Hugo static site generator
            "pipx",                         # Isolated python environments for packages
            "tmux",
        ]

    [packages.homebrew.server]
        casks = [

        ]
        formulae = [
            "ffmpeg",                       # Tools for dealing with audio and video
            "youtube-dl",                   # Tooling for downloading from youtube
        ]

    [packages.homebrew.personal_computer]
        casks = [
            "firefox",
            "omnifocus",
            "discord",
            "zoom",
            "obsidian",
            "cleanshot",
        ]
        formulae = [
        ]

    [packages.homebrew.sound_computer]
        casks = [
            "qlab",
            "omnifocus",
            "slack",
            "packetsender",
            "discord",
            "zoom",
            "obsidian",
            "cleanshot",
        ]
        formulae = [
            "nmap",                         # Port scanning utility
        ]

    [packages.asdf]
        plugins = [
            "golang",
            "nodejs",
            "python",
            "ruby",
        ]

    [packages.pipx]
        packages = [
            "poetry",                       # Python package and dependency manager
            "pre-commit",                   # Manage pre-commit hooks
            "argcomplete",                  # Needed for pipx autocompletions
        ]

    [packages.pipx.poetry]
        plugins = [
            "poetry-dynamic-versioning",    # Enable dynamic versioning based on VCS tags
            "poetry-plugin-export",         # Export the dependencies to various formats
        ]

    [packages.mas.common]
        apps = [
            "1592917505",                   # Noir
            "1365531024",                   # 1Blocker
            "409201541",                    # Pages
            "409203825",                    # Numbers
            "899247664",                    # TestFlight
            "1435957248",                   # Drafts
            "1607635845",                   # Velja
        ]

    [packages.mas.dev_computer]
        apps = [
            "497799835",                    # XCode
        ]

    [packages.mas.server]
        apps = [

        ]

    [packages.mas.personal_computer]
        apps = [
            "1529448980",                   # Reeder
            "1474335294",                   # GoodLinks
        ]

    [packages.mas.sound_computer]
        apps = [

        ]