[vscode]
    extensions = [
        "aaron-bond.better-comments",
        "davidanson.vscode-markdownlint",
        "dotenv.dotenv-vscode",
        "esbenp.prettier-vscode",
        "github.remotehub",
        "github.vscode-github-actions",
        "github.vscode-pull-request-github",
        "golang.go",
        "mechatroner.rainbow-csv",
        "ms-azuretools.vscode-docker",
        "ms-python.black-formatter",
        "ms-python.debugpy",
        "ms-python.flake8",
        "ms-python.python",
        "ms-python.vscode-pylance",
        "ms-vscode-remote.remote-containers",
        "ms-vscode-remote.remote-ssh-edit",
        "ms-vscode-remote.remote-ssh",
        "ms-vscode-remote.remote-wsl",
        "ms-vscode-remote.vscode-remote-extensionpack",
        "ms-vscode.remote-explorer",
        "ms-vscode.remote-server",
        "njpwerner.autodocstring",
        "tailscale.vscode-tailscale",
        "tamasfe.even-better-toml",
        "tyriar.sort-lines"
    ]